#!/bin/sh
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Onix 9 1 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Onix 2 19 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Onix 15 21 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Onix 10 21 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Charmander 5 5 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Charmander 5 5 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Charmander 6 6 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Charmander 6 6 1			
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Bulbasaur 3 9 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Bulbasaur 3 10 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Bulbasaur 3 11 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Bulbasaur 3 12 1			
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Squirtle 15 9 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Squirtle 25 9 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Squirtle 20 5 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Squirtle 1 50 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Snorlax 20 20 1	
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Snorlax 19 21 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Snorlax 18 22 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Snorlax 17 23 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Pikachu 7 10 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Pikachu 7 15 1			
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Pikachu 15 10 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Pikachu 15 12 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Raichu 19 19 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Raichu 21 21 1			
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Raichu 24 24 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Raichu 24 24 1	