./TP-Delibird_Game-Boy BROKER NEW_POKEMON Vaporeon 5 5 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Jolteon 8 7 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Jolteon 10 7 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Pikachu 9 9 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Flareon 11 11 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Charizard 3 3 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Bulbasaur 10 7 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Umbreon 15 15 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Espeon 1 1 1
./TP-Delibird_Game-Boy BROKER NEW_POKEMON Pidgey 2 6 1